# Generated by Django 3.2.4 on 2021-06-20 23:11

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210619_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='finished_after_deadline',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='finished_before_deadline',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.PositiveIntegerField(default=0, validators=[users.models.validate_rating]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_tasks_finished',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
