# Generated by Django 3.2.4 on 2021-06-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0002_task_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
